@api = http://localhost:3000/veiculos
GET {{api}}
###
GET http://localhost:3000/veiculosActivos
###
GET {{api}}/1
###

POST {{api}}
Content-Type: application/json

{
    "placa":"wlu9489",
    "id_tipo_veiculo":"1"
}
###
DELETE {{api}}/2
###

PUT {{api}}/1
Content-Type: application/json

{
   "placa":"777777",
    "id_tipo_veiculo":"1"
}